### ISSUE TITLE
Things to Research

### ISSUE THREAD

**Issue by HJohnson748** [Kody-Belisle/Diagnostic-Report-Generator#3]
**Things that need to be researched:**

- [ ] Research various Java report generators
- [ ] Research database options for Java. Built in or contact her web dev to link
- [ ] Research proper Java GUI elements
- [ ] Research how to make a .jar and independent runnable program
- [ ] Research license information for potential libraries

**Comment by HJohnson748** [comment]
Link to good demo tutorial for making a demo app with embedded database, all the way to a .jar.

https://www.oracle.com/technetwork/articles/javase/javadb-141163.html#integrating

**Comment by HJohnson748** [comment]
Looked into various report generator frameworks. Ended up choosing Pentaho.

https://help.pentaho.com/Documentation/8.2/Developer_Center/Embed_Reporting/In_Java_Application
