### ISSUE TITLE
Generate Report Button

### ISSUE THREAD

**Issue by Kody-Belisle** [Kody-Belisle/Diagnostic-Report-Generator#6]
As a user, I need to be able to generate a report so that I can send them to the appropriate clients.

**Acceptance Criteria:**
- [ ] Given user has entered data incorrectly, when the button is pressed, then a helpful error message is shown to the user.
- [ ] Given the user has entered the correct data but there is no report directory, when the button is pressed, then appropriately named directories are created and the appropriately named report is generated then placed in the proper directory.
- [ ] Given the user has entered the correct data and there is a directory created, when the button is pressed, then appropriately named directories are created and the appropriately named report is generated then placed in the proper directory.
